# This file lists external packages required to run and develop the framewortk.
#
# * Only top-level requirements are listed here.
# * You can use this file to set up a Conda environment:
#
#       conda env create -f environment.yml
#
# See also: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

name: MDOAirB_base

channels:
 - defaults

# List all explicitly imported/used packages
# ------------------------------------------
#
# Example -- Consider a Python file with following imports:
#
#   import package_A
#   import package_B
#
# Assume:
#
# ==> 'package_A' depends on 'package_B'
# ==> 'package_B' depends on a third 'package_C'
#
# 'package_A' and 'package_B' should be listed in this file since they
# are explicitly imported, but we do not list 'package_C'.

dependencies:
  - python=3.6

  # Required
  # Documentation
  - sphinx=3.0.3
  - pip
  - pip:
    - smt
    - pulp
    - tigl3
    - tixi3
    - cpacscreator
    - deap
    - numpy-stl
    - haversine
    - numpy
    - matplotlib
    - scipy
    - scikit-learn
    - pandas
    - vtk
    #- xmltodict>=0.12.0
    #- bokeh>=2.0.0
    - glpk
    #- numba>=0.5
    #- jsonschema>=3.2.0
    # Testing
    - flake8
    - pytest
    - pytest-cov
    - codecov

